### ISSUE TITLE
UnpicklingError: invalid load key, '\x09'.

### ISSUE THREAD

**Issue by LongDan15** [MarilynKeller/SMPL2AddBiomechanics#9]
(skel) ➜  SMPL2AddBiomechanics git:(main) ✗ python smpl2ab/smpl2addbio.py -i  /home/holmes/longdan/WHAM/output/demo/IMG_9732
Found 1 trials for subject IMG_9732
Traceback (most recent call last):
  File "smpl2ab/smpl2addbio.py", line 183, in <module>
    create_data_folder(subject_name=subject_name, 
  File "smpl2ab/smpl2addbio.py", line 53, in create_data_folder
    seq_data = load_smpl_seq(subject_trials[0]) # Load the first sequence
  File "/home/holmes/longdan/SMPL2AddBiomechanics/smpl2ab/utils/smpl_utils.py", line 16, in load_smpl_seq
    data_dict = pickle.load(open(smpl_seq_path, 'rb'))
_pickle.UnpicklingError: invalid load key, '\x09'.
(skel) ➜  SMPL2AddBiomechanics git:(main) ✗

**Comment by MarsXav** [comment]
Hi, I have the same issue with my own pkl SMPL motion, may I ask how you solve it?
